version: '3'
services:

  webapp:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    network_mode: "bridge"
    stdin_open: true
    tty: true
    command: sh startup.sh